### ISSUE TITLE
Permission denied - /tmp/cache/vendor (Errno::EACCES)

### ISSUE THREAD

**Issue by jschneiderhan** [flynn-archive/slugbuilder#29]
This isn't really an _issue_, just something that I was bitten by and figured I would share in case anyone else has a similar problem in the future.

If you are using [boot2docker](https://github.com/boot2docker/boot2docker) and are getting an error message similar to the following while trying to use the [caching](https://github.com/flynn/slugbuilder#caching) functionality, remember that the host directory needs to be present on the host of the Docker daemon (the boot2docker VM), not on your outermost host. If you create the directory within the boot2docker vm everything works like a charm.

```
docker run -v /tmp/app-cache:/tmp/cache:rw -i -a stdin -a stdout flynn/slugbuilder
```

... and are getting an error message like the following ...

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
/usr/lib/ruby/1.9.1/fileutils.rb:247:in `mkdir': Permission denied - /tmp/cache/vendor (Errno::EACCES)
        from /usr/lib/ruby/1.9.1/fileutils.rb:247:in `fu_mkdir'
        from /usr/lib/ruby/1.9.1/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `reverse_each'
        from /usr/lib/ruby/1.9.1/fileutils.rb:219:in `block in mkdir_p'
        from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `each'
        from /usr/lib/ruby/1.9.1/fileutils.rb:205:in `mkdir_p'
```

**Comment by jschneiderhan** [comment]
Closing since this isn't really an issue with the codebase
